-- PostgreSQL + TimescaleDB Schema for Neovance HIL System
-- Enable TimescaleDB extension
CREATE EXTENSION IF NOT EXISTS timescaledb;

-- Table 1: alerts (HIL State + Action Log - Hypertable)
-- This is the core time-series table for Human-in-the-Loop learning
CREATE TABLE alerts (
    id BIGSERIAL PRIMARY KEY,
    timestamp TIMESTAMPTZ NOT NULL,
    mrn VARCHAR(10) NOT NULL,
    risk_score FLOAT,
    features_json JSONB,  -- Critical: snapshot of all patient features used for AI prediction
    doctor_id VARCHAR(10),
    doctor_action VARCHAR(50),  -- 'Treat', 'Lab', 'Observe', 'Dismiss'
    action_detail TEXT  -- e.g., 'Ampi+Genta', '4 hours'
);

-- Convert alerts table into TimescaleDB hypertable
SELECT create_hypertable('alerts', 'timestamp');

-- Create indexes for efficient querying
CREATE INDEX idx_alerts_mrn ON alerts (mrn);
CREATE INDEX idx_alerts_doctor_id ON alerts (doctor_id);
CREATE INDEX idx_alerts_risk_score ON alerts (risk_score);
CREATE INDEX idx_alerts_features_json ON alerts USING GIN (features_json);

-- Table 2: outcomes (The Reward Signal - Standard Table)
-- Links delayed outcomes back to specific doctor actions
CREATE TABLE outcomes (
    id BIGSERIAL PRIMARY KEY,
    alert_id BIGINT NOT NULL REFERENCES alerts(id),  -- Foreign key to alerts table
    outcome_time TIMESTAMPTZ,  -- When outcome was determined
    sepsis_confirmed BOOLEAN,  -- THE BINARY REWARD: TRUE/FALSE for sepsis
    lab_result TEXT,  -- Detailed lab result
    patient_status_6hr VARCHAR(50),  -- 'Improved', 'Worsened', 'Stable'
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for outcome lookups
CREATE INDEX idx_outcomes_alert_id ON outcomes (alert_id);
CREATE INDEX idx_outcomes_sepsis_confirmed ON outcomes (sepsis_confirmed);

-- Table 3: realtime_vitals (High-frequency vitals from Pathway)
-- This replaces the SQLite live_vitals table
CREATE TABLE realtime_vitals (
    id BIGSERIAL PRIMARY KEY,
    timestamp TIMESTAMPTZ NOT NULL,
    mrn VARCHAR(10) NOT NULL,
    hr FLOAT,  -- Heart rate
    spo2 FLOAT,  -- SpO2 percentage
    rr FLOAT,  -- Respiratory rate
    temp FLOAT,  -- Temperature
    map FLOAT,  -- Mean arterial pressure
    risk_score FLOAT,  -- EOS risk score
    status VARCHAR(20),  -- ROUTINE_CARE, ENHANCED_MONITORING, HIGH_RISK
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Convert realtime_vitals to hypertable for high-frequency data
SELECT create_hypertable('realtime_vitals', 'timestamp');

-- Indexes for realtime vitals
CREATE INDEX idx_realtime_vitals_mrn ON realtime_vitals (mrn);
CREATE INDEX idx_realtime_vitals_status ON realtime_vitals (status);

-- Table 4: babies (Patient information)
-- Migrate from existing baby data
-- Clean schema setup for PostgreSQL/TimescaleDB
-- Drop existing tables with CASCADE to handle dependencies
DROP TABLE IF EXISTS outcomes CASCADE;
DROP TABLE IF EXISTS alerts CASCADE;
DROP TABLE IF EXISTS realistic_vitals CASCADE;

-- Table to store alerts generated by the ML model and subsequent human-in-the-loop actions
CREATE TABLE alerts (
    alert_id SERIAL PRIMARY KEY,
    baby_id TEXT NOT NULL,
    timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    
    -- Model Prediction Details
    model_risk_score FLOAT,
    onset_window_hrs INT,
    alert_status TEXT DEFAULT 'PENDING_DOCTOR_ACTION', -- PENDING_DOCTOR_ACTION, ACTION_TAKEN, CLOSED
    
    -- Doctor's Action (HIL)
    doctor_id TEXT,
    doctor_action TEXT, -- e.g., OBSERVE, TREAT, LAB_TEST, DISMISS
    action_detail TEXT,
    action_timestamp TIMESTAMPTZ,
    
    -- Final Outcome and Reward
    sepsis_confirmed BOOLEAN,
    outcome_timestamp TIMESTAMPTZ,
    reward_signal INT, -- +1 for correct, -1 for incorrect
    model_status TEXT -- SUCCESS, FAILURE
);

-- Table to store generated realistic vital signs
CREATE TABLE realistic_vitals (
    id SERIAL PRIMARY KEY,
    baby_id TEXT NOT NULL,
    timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    hr FLOAT,
    spo2 FLOAT,
    resp_rate FLOAT,
    temp FLOAT,
    map FLOAT,
    risk_score FLOAT,
    status TEXT
);

-- Create indexes for faster queries
CREATE INDEX idx_alerts_status ON alerts(alert_status);
CREATE INDEX idx_alerts_baby_id ON alerts(baby_id);
CREATE INDEX idx_alerts_timestamp ON alerts(timestamp);
CREATE INDEX idx_vitals_timestamp ON realistic_vitals(timestamp);
CREATE INDEX idx_vitals_baby_id ON realistic_vitals(baby_id);


-- Sample data for testing
INSERT INTO babies (mrn, name, gestational_age_weeks, birth_weight, current_weight, maternal_gbs, maternal_fever, rom_hours, antibiotics_given) 
VALUES 
('B001', 'Amelia Rodriguez', 37, 2.8, 2.9, 'negative', false, 6.0, false),
('B002', 'Lucas Chen', 35, 2.2, 2.3, 'positive', true, 18.0, true),
('B003', 'Sophie Williams', 39, 3.1, 3.2, 'unknown', false, 4.0, false);

-- HIL Analytics Views
-- View 1: Latest vitals per patient
CREATE VIEW latest_vitals AS
SELECT DISTINCT ON (mrn)
    mrn, timestamp, hr, spo2, rr, temp, map, risk_score, status
FROM realtime_vitals
ORDER BY mrn, timestamp DESC;

-- View 2: Doctor action summary
CREATE VIEW doctor_action_summary AS
SELECT 
    doctor_id,
    doctor_action,
    COUNT(*) as action_count,
    AVG(risk_score) as avg_risk_score,
    DATE_TRUNC('day', timestamp) as action_date
FROM alerts
WHERE doctor_action IS NOT NULL
GROUP BY doctor_id, doctor_action, DATE_TRUNC('day', timestamp)
ORDER BY action_date DESC, action_count DESC;

-- View 3: HIL learning dataset (alerts with outcomes)
CREATE VIEW hil_training_data AS
SELECT 
    a.id as alert_id,
    a.timestamp,
    a.mrn,
    a.risk_score,
    a.features_json,
    a.doctor_action,
    a.action_detail,
    o.sepsis_confirmed,
    o.patient_status_6hr,
    (o.sepsis_confirmed IS TRUE) as positive_outcome
FROM alerts a
LEFT JOIN outcomes o ON a.id = o.alert_id
WHERE a.doctor_action IS NOT NULL;

-- Retention policy for high-frequency data (optional)
-- Keep detailed vitals for 30 days, then downsample
-- SELECT add_retention_policy('realtime_vitals', INTERVAL '30 days');

COMMENT ON TABLE alerts IS 'Core HIL table: AI predictions + doctor actions for supervised learning';
COMMENT ON TABLE outcomes IS 'Delayed reward signals linked to doctor actions';
COMMENT ON TABLE realtime_vitals IS 'High-frequency time-series vitals from Pathway ETL';
COMMENT ON COLUMN alerts.features_json IS 'JSONB snapshot of all patient state used for AI prediction';
COMMENT ON COLUMN outcomes.sepsis_confirmed IS 'Binary reward signal for HIL learning';